import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          ยินดีต้อนรับเข้าสู่ PG <a href="https://watafak88.com">SLOT ALL</a>
        </h1>

        <p className={styles.description}>
          เริ่มต้นความสนุกได้ที่ 
        </p>

        <div className={styles.grid}>
          <a href="https://watafak88.com/#/register" target="_blank" rel="noopener noreferrer" className={styles.card}>
            <h2>สมัครสมาชิก &rarr;</h2>
            <p><strong>สมัครเล่น PGSLOT</strong> ค่ายเกมคาสิโนออนไลน์เปิดใหม่ ที่กำลังเป็นจุดสนใจจากนักเดิมพันมืออาชีพ</p>
          </a>

          <a href="https://watafak88.com/#/playgame" target="_blank" rel="noopener noreferrer" className={styles.card}>
            <h2>เข้าเล่นเกมส์ &rarr;</h2>
            <p><strong>ทางเข้าเล่น PG SLOT</strong>สามารถเข้าเล่นได้หลากหลายแพลตฟอร์มทั้งโทรศัพท์มือถือ คอมพิวเตอร์ แท็บเลต</p>
          </a>

          <a
            href="https://watafak88.com/#/credit"
            target="_blank" rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>รับเครดิตฟรี &rarr;</h2>
            <p>แจกเครดิตฟรี 30 บาท ทำตามขั้นตอนง่ายๆ เพียงแค่ 3 ขั้นตอน**</p>
          </a>

          <a
            href="https://www.pgslot-free.com/"
            target="_blank" rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>ทดลองเล่นฟรี &rarr;</h2>
            <p>
            ทดลองเล่นฟรีแบบไม่อั้น กับเกมส์หลากหลาย Style แบบจุใจได้ที่นี่
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
